### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by jerkimball** [enricosada/LightTable-FSharp#4]
Can't Ctrl-Enter w/Selection, can't connect to project.

Error text follows:

We couldn't connect.

Looks like there was an issue trying to connect to the project. Here's what we got:

Microsoft (R) F# Interactive version 12.0.30110.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

stdin(0,1): error FS0206: Problem with filename '"C:\Users\XXX\AppData\Local\LightTable\plugins\F#\fs-src\ltfsclient\ltfsclient.fsx"': Illegal characters in path.

**Comment by cascadian** [comment]
I got the same error

**Comment by TeaDrivenDev** [comment]
There's a pair each of single and double quotes around the file name; I think the double quotes may be too much. I haven't been able to find out yet where those would get put in, though.

**Comment by aadamsx** [comment]
Same error here on Windows 8.1

**Comment by mlf2278** [comment]
The added double quotes on Windows seem to be causing this issue.  Removing them fixed it here.

You can either fix the escape-spaces function in fsharp.cljs in the plugin directory and rebuild it or fix the corresponding generated javascript (f#_compiled.js at the root of the F# plugin) function (on line 80 here), modified as shown below (added "ee" near the end, so that the test does not match, ugly but it works):

lt.plugins.fsharp.escape_spaces = (function escape_spaces(s){if(cljs.core._EQ_.call(null,lt.objs.files.separator,"ee\"))

**Comment by enricosada** [comment]
fixed in version 0.2.1, thx all
